PRA/PRA/Controllers/HomeController.cs
using PRA.DBQuizard;
using PRA.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRA.Controllers
{
    public class HomeController : Controller
    {
        private DBQuizardEntities _context;

        public HomeController()
        {
            _context = new DBQuizardEntities();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult PrijavljeniKorisnik()
        {
            string email = Session["userEmail"].ToString();
            UserAcc user = _context.UserAcc.SingleOrDefault(u => u.Email == email);
            IList<Quiz> quizzes = _context.Quiz.Where(q => q.UserAccID == user.IDUserAcc).ToList();
            UserIKvizovi userIKvizovi = new UserIKvizovi
            {
                User = user,
                Quizovi = quizzes
            };
            return View(userIKvizovi);

        }
    }
}

PRA/PRA/Controllers/JoinQuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRA.Controllers
{
    public class JoinQuizController : Controller
    {
        // GET: JoinQuiz
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Join()
        {
            return View();
        }
    }
}

PRA/PRA/Controllers/QuizController.cs
using PRA.DBQuizard;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRA.Controllers
{
    public class QuizController : Controller
    {
        private DBQuizardEntities _context;

        public QuizController()
        {
            _context = new DBQuizardEntities();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Quiz
        public ActionResult Index()
        {
           return View();
        }




    }
}

PRA/PRA/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PRA/PRA/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PRA/PRA/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div style="background-color:white; padding: 0" class="jumbotron">
    <h1 style="text-align:center">DOBRODOŠLI :)</h1>
    <h3>Koristi linkove na headeru za korištenje stranice</h3>
    <h3>Puno sreće, trebat će ti</h3>
</div>

PRA/PRA/Views/Home/PrijavljeniKorisnik.cshtml
@model PRA.ViewModels.UserIKvizovi
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quizard", "PrijavljeniKorisnik", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Napravi kviz", "Index", "JoinQuiz")</li>
                    <li>@Html.ActionLink("Prodruži se kvizu", "Join", "Quiz")</li>
                </ul>
            </div>
        </div>
    </div>
</body>
</html>

@*<img class="img-circle" width:"100px;" height:"100px;" runat="server" style="border: 2px; "/>*@

<h1>Dobrodošli @Model.User.Username</h1>


<div class="form-group">
    
    <a href="https://localhost:44305/Quizs/Create" class="btn btn-primary" style="margin-top: 15px;">Kreiraj quiz</a>
    <a href="https://localhost:44305/Home/Index" class="btn btn-primary" style="margin-top: 15px;"> Odjava </a>
</div>

<table class="table-bordered table" style="margin-top:2%">
    <thead>
        <tr>
            <td>Naziv kviza</td>
            <td>Izbriši</td>
        </tr>
    </thead>
    <tbody>
       @foreach (var kviz in Model.Quizovi)
            {
                <tr>
                    <td>@Html.ActionLink(kviz.Title, "Edit", "Quiz", new { id = kviz.IDQuiz }, null)</td>
                    <td>@Html.ActionLink("Izbriši", "Delete", "Quiz", new { id = kviz.IDQuiz })</td>
                </tr>
            }
    </tbody>
</table>